### ISSUE TITLE
Exposición «Sistemas basados en grid»: Preguntas y respuestas

### ISSUE THREAD

**Issue by gwolf** [unamfi/sistop-2021-2#136]
Abro este foro como un espacio de discusión para la exposición que prepararon los alumnos Oswaldo Cabrera y Hanna Ceres, «Sistemas basados en grid». El video está disponible en:

https://youtu.be/FexnbGHTMJE

Pueden consultar también el [documento de texto en que los alumnos presentan este mismo tema](./CabreraOswaldo-CeresHanna/Sistemas_basados_en_Grid.pdf).

Además de participar aquí, les pido que llenen la pequña encuesta que está disponible en:

https://www.questionpro.com/t/ARiwuZnUrc

**Comment by Aom92** [comment]
Hola! Me pareció bastante interesante su exposición. La única duda que me surgió es en el algoritmo de selección en caso de que el nodo líder comience a deteriorarse que criterios se toma para volver a convocar a una nueva elección de líder.

**Comment by HannCM** [comment]
> Hola! Me pareció bastante interesante su exposición. La única duda que me surgió es en el algoritmo de selección en caso de que el nodo líder comience a deteriorarse que criterios se toma para volver a convocar a una nueva elección de líder. 

@Aom92 hola!
Va a depender de la razón por la cual se deterioró el nodo líder. Por ejemplo, si se cae el servidor se elegiría el que involucre el proceso con menos actividad (para balancear las cargas). Entonces los nodos se comunicarán entre si, repitiendo el algoritmo para elegir a el mejor nuevamente. :)

**Comment by OswaCabrera** [comment]
> Hola! Me pareció bastante interesante su exposición. La única duda que me surgió es en el algoritmo de selección en caso de que el nodo líder comience a deteriorarse que criterios se toma para volver a convocar a una nueva elección de líder.

Hola @Aom92, estamos contentos de que te haya parecido interesante nuestra exposición :), agregando a lo que ya te comentó mi compañera @HannCM, puede haber varios motivos por lo cual se convoque a una elección. Por ejemplo:
* El hecho de que se perdió comunicación con el nodo líder por alguna razón
* Que el sistema de comunicación donde se encontraba el nodo (puede haber varias redes de comunicación) se cayó
* Se detectó que el nodo líder trabaja de manera errónea intencionalmente (falla bizantina) 
* El mismo nodo puede determinar que sus recursos (como batería) se están agotando o deteriorando y llamar a una selección (esto sería una prevención, y es por esto que en nuestro algoritmo presentado cada nodo envía información sobre su estado y el de sus recursos para así escoger al que esté en mejores condiciones para ser el líder)
*  También simplemente se puede programar que cada cierto tiempo se haga una elección para escoger un nuevo nodo líder.

Espero tu duda haya quedado resuelta :) si no, o si tienes alguna otra duda por favor háznoslo saber :). Gracias !

**Comment by Franperceb** [comment]
Qué tal!, me pareció un tema muy interesante , claro y muy bien explicado de parte de ambos. Considero que el grid computing  es muy benéfico ya que permite desarrollar  y ejecutar  aplicaciones más robustas pues  modulariza un problema a resolver en diferentes secciones de trabajo. Una duda que me surgió respecto al tema es  si se maneja algún protocolo de seguridad ya que puede ser contraproducente que se compartan ciertos recursos o información indebida entre los cómputos.

**Comment by HannCM** [comment]
> Qué tal!, me pareció un tema muy interesante , claro y muy bien explicado de parte de ambos. Considero que el grid computing  es muy benéfico ya que permite desarrollar  y ejecutar  aplicaciones más robustas pues  modulariza un problema a resolver en diferentes secciones de trabajo. Una duda que me surgió respecto al tema es  si se maneja algún protocolo de seguridad ya que puede ser contraproducente que se compartan ciertos recursos o información indebida entre los cómputos. 


Hola, buenas noches @Franperceb!

Sí, si existen muchos otros protocolos para cuidar los recursos y la información en el Grid Computing. En nuestra exposición por tiempo solo abarcamos uno que es el de Cliente-Servidor.
De hecho es un subtema muy interesante para investigar y hablar.

A continuación te platicaré brevemente de un protocolo llamado "Asignación de recursos":

Trabaja con un proxy de recursos, que es una entidad encargada de planificar el acceso al recurso y mapearlo. Sus tareas son verificar primeramente que las solicitudes de recursos del proxy usuario ( otro protocolo encargado de cuidar de las credenciales de usuario y sus roles)  sean válidas, en dado caso que así sea le proporciona los recursos pedidos y lo registra. El proxy recursos le proporcionará también una credencial temporal mientras realiza los procesos. 

Este protocolo es muy importante porque cuida la información y recursos que se comparte. 

Espero haberte ayudado :))

**Comment by gwolf** [comment]
@Aom92, @Franperceb: ¡Gracias por su participación! Recuerden que los algoritmos que los compañeros presentaron son ejemplos de cómo podrían implementarse, y en todo caso, la implementación en situaciones específicas de problemas reales requiere de "llenar los huecos" según lo requiera cada uno de los problemas abordados.

Cierro esta área de preguntas y respuestas. ¡Gracias a @HannCM y a @OswaCabrera por su trabajo!
