### ISSUE TITLE
 Exposición «Graphics Output Protocol»: Preguntas y respuestas

### ISSUE THREAD

**Issue by gwolf** [unamfi/sistop-2021-2#139]
Abro este foro como un espacio de discusión para la exposición que preparó el alumno Hugo Juárez Pérez, «Graphics Output Protocol». El video está disponible en:

https://youtu.be/Ip5RBe8xiq4

Pueden consultar también el [documento de texto en que el alumno presenta este mismo tema](https://raw.githubusercontent.com/unamfi/sistop-2021-2/main/exposiciones/JuarezPerezHugo/GraphicsOutputProtocol.pdf).

Además de participar aquí, les pido que llenen la pequña encuesta que está disponible en:

https://www.questionpro.com/t/ARiwuZnX9A

**Comment by LuisMPS** [comment]
Hola, Hugo!
Me gustó tu expo y aprendí sobre lo que presentaste, especialmente porque no estoy muy metido en cosas de gráficos.

Tengo una pregunta sencilla.
Dices que el GOP es parte de la especificación UEFI, y me imagino que es mayormente útil en el arranque. Mi pregunta es si este protocolo de gráficos es útil para algo una vez que el sistema operativo arranca y el controlador de gráficos toma el control. Dices que todavía hay algunas funciones del GOP que se pueden utilizar después del arranque como el "Framebuffer" del GOP. Sólo me gustaría que aclararas, o dieras algunos ejemplos, sobre para que cosas se puede utilizar más adelante del arranque. 

Y si puedes, también mencionarme rápidamente que es exactamente un framebuffer. Como no estoy muy enterado de gráficos, me perdí con eso. 

Gracias!

**Comment by Aom92** [comment]
> Tengo una pregunta sencilla.

> Y si puedes, también mencionarme rápidamente que es exactamente un framebuffer. Como no estoy muy enterado de gráficos, me perdí con eso.

Con gusto respondo a tu pregunta! 
Un ***Framebuffer***, en pocas palabras es el lugar a donde nosotros decimos que se quiere dibujar algun pixel en pantalla y ese lugar se encuentra en la memoria de nuestro dispositivo de salida. Guardamos los pixeles en el framebuffer para que despues los valores almecenados son transformados en las señales que debe leer el monitor. 

Con respecto a tu segunda pregunta
> Mi pregunta es si este protocolo de gráficos es útil para algo una vez que el sistema operativo arranca y el controlador de gráficos toma el control. 

La respuesta es no, para cualquier sistema operativo convencional una vez cargados estos tienen su propio controlador de video y ya este se encarga de realizar las tareas de gráficos. Un caso en el que el sistema operativo tenga ya en ejecución tenga que usar GOP seria cuando alguien este realizando un S.O. desde cero  y no cuentes con un controlador de video. ahí dependerías totalmente de utilizar GOP para poder obtener imágenes en pantalla.

**Comment by HannCM** [comment]
Buenas noches, Hugo :)

Acabo de ver tu exposición y supiste atrapar mi atención desde que hiciste imaginarme en esa situación.
 
Quisiera que me explicaras mejor cómo GOP depura los errores que se dan con una falla en el hardware. Si puedes con un ejemplo sería muy útil. 

Gracias!

**Comment by Aom92** [comment]
> Quisiera que me explicaras mejor cómo GOP depura los errores que se dan con una falla en el hardware. 


Buenas noches, primero que nada GOP no depura los errores en caso de una falla de hardware, más bien con GOP representas la salida de algún mecanismo que se haya diseñado para encontrar alguna falla de hardware antes del arranque del S.O.

> Si puedes con un ejemplo sería muy útil.

Un ejemplo de como utilizar GOP junto con otros mecanismos seria justamente la primera llamada al GOP, ya que si no se puede acceder a el algo anda terriblemente mal ya sea un fallo físico con la GPU o que la GPU utilizada no sea compatible. 

```C
...

status = uefi_call_wrapper(BS->LocateProtocol, 3, &gopGuid, NULL, (void**)&gop);                                         
if(EFI_ERROR(status))
{
    PrintLn(L"Unable to locate GOP");
    return 
}

...
```
La clave de esto es utilizar la variable status en conjunto con la funcion EFI_ERRROR, si el resultado de status es distinto a EFI_SUCCESS terminaria la ejecucion del bloque de codigo y con esto nos damos una idea de que pudo haber salido mal. 

En lo que abarca mi entendimiento tener herramientas para depurar codigo de bajo no suelen ser muy detalladas asi como los errores en lenguajes de alto nivel que pude arrojar un codigo en python o incluso C++

**Comment by OswaCabrera** [comment]
Hola Hugo! Tu exposición me pareció sumamente interesante por una situación que me pasó hace no mucho. Me llegó una actualización de windows 10 y no sé en que momento del proceso de actualización mi pantalla se tornó como te muestro en la imagen. Apagaba y prendía mi computadora pero me lanzaba la misma imagen. Pensaba que lo más probable esque había sido un daño físico. Pero mientras experimentaba e investigaba sobre que podía hacer, me dí cuenta de que podía ingresar a la BIOS :0, y me la mostraba sin ninguna distorsión como cuando intentaba entrar a Windows. Entonces, ¿fue el GOP lo que me permitió poder visualizar el BIOS? ¿Es lo mismo UEFI que BIOS (tenía entendido que se tenía uno u otro pero no ambos? ¿o el UEFI es parte del BIOS? 

Esas son mis preguntas, gracias :)   

![IMG_1660](https://user-images.githubusercontent.com/79554682/124544331-877bf400-ddec-11eb-8c31-d772afe1227d.jpg)

**Comment by Aom92** [comment]
>¿Es lo mismo UEFI que BIOS (tenía entendido que se tenía uno u otro pero no ambos)?
Hacen la misma tarea sin embargo UEFI es la  _versión mejorada_ del BIOS. Todas las computadoras recientes cumplen con el estándar UEFI

>¿fue el GOP lo que me permitió poder visualizar el BIOS?
Si tu laptop fue comprada después del  2010. Si puedo decir con certeza que fue el GOP que te dejo visualizar el menú BIOS.


Es importante aclarar que UEFI es la versión mejorada del BIOS, pero el nombre de aquel menú de opciones donde configuramos nuestro sistema se le sigue llamando BIOS lo cual puede confundir bastante.

**Comment by Franperceb** [comment]
Que tal Hugo!. Me pareció muy interesante lo explicado respecto al GOP y muy claro. No tengo un gran conocimiento respecto a entorno gráfico y relacionados y veo que tienes un amplio conocimiento del tema, es por ello que te quiero preguntar si Legacy VGA VBE BIOS es algo parecido al GOP o no tiene nada que ver, anteriormente me encontre con un artículo que mencionaba al respecto

**Comment by Aom92** [comment]
>Si Legacy VGA VBE BIOS es algo parecido al GOP o no tiene nada que ver, anteriormente me encontre con un artículo que mencionaba al respecto

Así es, son parecidos por que justamente el propósito del GOP es reemplazar toda la funcionalidad que proporcionaba VGA VBE BIOS.

**Comment by gwolf** [comment]
¡Muchas gracias, @Aom92, por tu presentación y tus muy buenas respuestas! Hago un par de precisiones, antes de cerrar este espacio de preguntas y respuestas.
- Para la pregunta de @LuisMPS: Un _framebuffer_ es un arreglo de memoria que se mapea directamente (sin aceleración de ningún tipo) a los pixeles de una pantalla. Es el modo más simple (no necesariamente más eficiente) de representar a la salida gráfica de un sistema.
- @OswaCabrera, la respuesta que te dio Hugo es técnicamente correcta, pero ya saben que me encanta meterme a peinar los detallitos más finos ;-). Desde hace ya varios años, es erróneo decir que las computadoras personales tienen BIOS. El BIOS se refiere a un conjunto de especificaciones de inicio, verificación, inicialización del hardware y transferencia de control al sistema operativo que desarrolló IBM para su PC en 1981 (con varias adiciones, pero a fin de cuentas es eso). UEFI es su sucesor. No es una nueva versión ni una versión mejorada: Es una reimplementación completamente distinta, que no necesariamente guarda compatibilidad (aunque muchas implementaciones de UEFI tienen un modo de "emulación de BIOS").

¡Gracias a todos por su participación!
